---
title: "Lit review for SSLA replication special issue"
subtitle: "Speech perception in noise"
author: "RAP group"
date: "Last update: `r Sys.Date()`"
classoption: 10pt
csl: apa-6th-edition.csl
bibliography: speech_in_noise.bib
nocite: '@*'
output:
  pdf_document: default
  github_document: default
knit: (function(inputFile, encoding){
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = ".", output_format = "all") })
---

# Big picture

**Speech in noise**  

Less intense regions of the speech signal can be masked and rendered unintelligible by extraneous noise in the acoustic environment (Helfer & Wilbur, 1990). 
Thus, speech perception in noise is more difficult due to the decreased amount of acoustic and linguistic cues available to the listener. 
Speech perception becomes more difficult as the signal to noise ratio decreases. 
This is particularly true in one's non-native language, referred to in the literature as the 'native advantage'.
Some studies show that this difficulty persists even when one learns their L2 at an early age.  

**Questions**  

- Why is it hard to hear an L2 in background noise?
- Do early learners have more difficulty perceiving speech in noise than monolinguals?

According to Scharenborg (2019), the native advantage results from 'imperfect knowledge' of the L2, but it seems unlikely that early bilinguals have imperfect knowledge. 





# Previous lit

## AoA

- @mayo_1997
- @meador_flege_mackay_2000
- @rogers_etal_2006
- @shi_2010 
- @tabri_2011
- @lee_2014
- @reetzke_2016

## Native vs. non-native

- Borghini and Hazan, 2018; 
- Bradlow and Alexander, 2007;
- Scharenborg et al., 2018a
- @ezzantian_2010

## Level of abstraction

**Phoneme perception** (not word level):

- Broersma and Scharenborg, 2010; 
- Cooke et al., 2010; 
- Garcia Lecumberri et al., 2006

## Method papers

- @mayo_1997
- 2002_vanwijngaarden

\clearpage

# NOTES

## Acronyms

- SPL: sound pressure level (dB)
- SNR: signal to noise ratio (positive: speech signal is stronger than background noise; negative: noise is stronger)
- SSN: speech shaped noise
- SPIN: speech perception in noise test (Kalikow et al, 1977)
- SRT: speech reception threshold test, similar to NTL
- NTL: noise tolerance level (point at which listener discriminates targets at 50% accuracy)

## @mayo_1997

- purpose: determin how AoA influences SLA speech
- test: SPIN (12 speaker babble, dont report SNR)
- participants: simultaneous bilinguals, early-sequential bilinguals (<6), late-sequential bilinguals (>14), monolinguals
- n: 3, 9, 9, 9
- languages: Spanish, English
- L2 proficiency: no measure
- findings: 
  - levels of noise at which the speech was intelligible were significantly higher for monolinguals and early bilinguals than for late bilinguals
  - benefit from context was significantly greater for monolinguals and early bilinguals than for late bilinguals
  - "early bilinguals...may not function at the same level as monolinguals, who demonstrate higher NTLs and steeper psychometric functions. Although early second-language acquisition is advantageous for listening in noise, interference from a first language may reduce even an early-bilingual listener’s ability to perceive second-language speech in noise."

## @meador_flege_mackay_2000

- purpose: study word recognition in a second language taking into account cross-language differences in sound inventories
- test: English sentences presented in noise, DV: \# of correct words repeated
  - pink noise, snl: -6, 0, 6, 12
- participants: Monolingual English, early-low (7), early (7), mid (14), late (19)
- n: 18, 18, 18, 18, 18
- languages: Italian, English
- L2 proficiency: none
- findings: 
  - higher word recognition scores were obtained for early than late bilinguals
  - higher word recognition scores were obtained for early bilinguals who used Italian seldom than for early bilinguals who used Italian relatively often
  - ability to perceive English vowels and consonants accounted for a signifcant amount of variance in the word-recognition scores
- notes: AoA in this study is mean age of arrival (not acquisition, and no cut-off), early-low and early groups have same AoA mean, but early-low reported less L1 use (8% vs. 32%)

## @rogers_etal_2006

- purpose: explore effects of early bilingualism on adults' speech perception in adverse listening environments (noisy and reverberant) (few studies with early learners, they dont look at proficiency, i.e., Mayo et al, and don't include participants w/o foreign accent, i.e., Meador et al)
- test: CID W22 (SSN, SSN + reverberation)
  - Speech Intelligibility Gain—Reverberant (SIG-R) Test (Koehnke & Besing, 1996), SNR: 4, 2, 0
  - Noisy w-22, SNR: -6, -2, 0
- participants: monolingual, early bilingual
- n: 15, 12
- languages: Spanish, English
- L2 proficiency: self-report questionnaire
- findings: 
  - poorer word recognition scores for bilingual listeners than for the monolingual listeners under conditions of noise and noise with reverberation, but not in quiet.

## @shi_2010 

- purpose: effects of acoustic degradation and context use on sentence perception were evaluated in listeners differing in age of English acquisition.
- test: identified target words in 400 Speech-Perception-in-Noise (SPIN, same as Mayo et al) sentences presented in 
  - noise (+6 vs. 0 dB signal-to-noise ratio)
  - reverberation (1.2 vs. 3.6 s reverberation time),
  - context (high vs. low predictability)
- participants: monolingual, simultaneous bilingual, early-sequential (<7), late-sequential, very-late sequential
- n: 8, 8, 8, 8, 8
- languages: various L1s
- L2 proficiency: LEAP-Q, self-report
- findings: 
  - effect of noise, as well as the combined effect of reverberation and context, was mediated by age of acquisition
  - simultaneous and early bilinguals use of context, by contrast, deviated substantially from the monolingual normative in difficult listening conditions.

## @tabri_2011

- purpose: "bilinguals have a deficit in speech perception for their second language compared with monolingual speakers under unfavourable listening conditions"
- test: SPIN test (12 speaker babble), SNR: 0, +5, +10, +15, +20
- participants: monolingual, early bilingual (<6), early trilingual (<6)
- n: 9, 13, 12
- languages: arabic, french, english
- L2 proficiency: 'fluency' in English tested: interview and questionnaire (knowledge and use)
- findings: 
  - performance declined more rapidly in noise (at 65 and 70 dB SPL)
  - Trilingual listeners performed less well than bilinguals, but not significant 
  - subgroup of five simultaneous bilinguals equivalent to monolinguals

## @lee_2014

- purpose: investigate heritage speakers' speech perception in noise (SPIN) compared with second language (L2) learners and native speakers of Korean
- test: custom SPIN
- participants: monolinguals, late learners, heritage learners
- n: 14, 20, 32
- languages: korean, english
- L2 proficiency: IRL korean test
- findings: 
  - early exposure, even if limited, to the second language has a positive effect on speech perception in noise in the language
  - Heritage speakers ability to perceive speech in noise was similar to native speakers'

## @reetzke_2016

- purpose: 
- test: 
- participants: 
- n: 
- languages: 
- L2 proficiency:
- findings: 


## Scharenborg (2019)

> Imperfect knowledge of the language and the presence of background noise interact strongly to our disadvantage 

- What constitutes imperfect knowledge?  
Seems unlikely that early bilinguals have imperfect knowledge
- Focus has been on phoneme perception (native advantage)
- More recent studies on work recognition (also native advantage)

Why though? Hard to say because of...

- different studies, 
- different research methodologies, 
- different stimuli, 
- different tasks, 
- different noise levels, 
- different types of noise, 
- different groups of participants, 
- different language backgrounds, 
- different proficiency levels, 
- and NO systematic comparison of these studies

**Most common methodology**:

- (16 out of 23 studies in review)
- select a number of different SNRs, 
- present the target speech signal at a fixed level of intensity at these different SNRs, 
- and calculate the number or percentage of correctly identified words

**Noise types**:

- Energetic vs informational masking
- white noise has a larger negative effect on non-native word recognition than pink and aircraft noise.


# MAIN POINT

> These studies concluded that even early bilinguals who perform in a native-like way in quiet, are more adversely affected by noise than their monolingual peers, possibly because of interference of their other language(s). 
However, groups of simultaneous early bilinguals in these studies were often very small (N = 3 in both Mayo et al. and Rogers et al.), so more research is needed to investigate whether these results generalise to larger and other listener groups.

> In summary, early bilinguals and high-proficiency non-native listeners perform native-like in quiet and relatively easy listening conditions with low levels of noise. However, in more difficult listening conditions, non-natives perform worse than native listeners, regardless of their pro- ficiency levels and regardless of the method used to determine their proficiency (be it objective or subjective measures). Even early bilin- guals are adversely affected by background noise during word recognition compared to monolingual native listeners. **These results show the importance of the age of acquisition of the non-native language and proficiency in the non-native language on listeners’ performance in word recognition in noise tasks**. To account for inequivalent proficiency levels and to improve comparability of the results across studies, future in- vestigations into the effect of background noise on non-native listening should include objectively measured individuals’ non-native proficiency levels (see also Kilman et al., 2014; Scharenborg et al., 2018a).


\clearpage

# References
